name: CI-Test

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Force Xcode 12
      run: sudo xcode-select -switch /Applications/Xcode_12.2.app
    - name: Run tests
      run: xcodebuild clean test -project "Experiments.xcodeproj" -scheme "Experiments" -destination "platform=iOS Simulator,name=iPhone 11 Pro Max,OS=latest"
    - name: Build App
      run: xcodebuild -project "Experiments.xcodeproj" -scheme "Experiments" -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO

